### ISSUE TITLE
Coturn server crashes

### ISSUE THREAD

**Issue by watanabejr** [coturn/coturn#36]
I build source code coturn and libevent, then install them in CentOS 6.5. STUN and TRUN access seems to be working correct.
But, when I send http query request without "=" and value  like http://&lt;ip address&gt;:&lt;port&gt;?key, coturn server crashes because of segmentation fault. 
Coturn server does not crash when I send http query with ?key= or ?key=value.

Here is the syslog.
```
Feb 26 11:44:50 host-192-168-10-9 kernel: turnserver[19668]: segfault at 8 ip 000000000040fe8e sp 00007f3c6dd12220 error 6 in turnserver[400000+6a000]
Feb 26 11:44:50 host-192-168-10-9 abrtd: Directory 'ccpp-2016-02-26-11:44:50-19660' creation detected
Feb 26 11:44:50 host-192-168-10-9 abrt[19674]: Saved core dump of pid 19660 (/usr/local/bin/turnserver) to /var/spool/abrt/ccpp-2016-02-26-11:44:50-19660 (86544384 bytes)
```

I want not to stop coturn when the server receives any query.
Is this a bug? Otherwise, could you please tell me how to avoid?

Thanks.

**Comment by mom040267** [comment]
I ll check the problem and i ll let you know

**Comment by mom040267** [comment]
I was able to reproduce the issue.

I'll fix it.

**Comment by mom040267** [comment]
I fixed the problem in the master branch.

**Comment by watanabejr** [comment]
Thank you for the quick response.

I confirmed that coturn does not crash when I send query of this issue.
But, it seems any http response is not returned to my client. Is it a correct behavior?

**Comment by mom040267** [comment]
not "any", only badly formed HTTP requests.

I'll adjust it so an error will be returning.

**Comment by mom040267** [comment]
I fixed that.

**Comment by watanabejr** [comment]
Sorry for my poor English.

I confirmed that logon page is returned when I send bad format HTTP requests.  

Thank you for your time.

**Comment by muabada** [comment]
Apr  9 08:42:40 JVBNA kernel: [252318.145277] turnserver[10065]: segfault at 7ff0d0000078 ip 00007ff0d0000078 sp 00007ff0d5999958 error 15

Still getting this issue, turn server keeps crashing : 

Version : Version Coturn-4.5.0.5 
OS : 
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.8 (stretch)
Release:	9.8
Codename:	stretch
